--Constantes partagées entre master et slave

MISO_CHANNEL = 42069
MOSI_CHANNEL = 42070

MOSI_PREFIX = "MOSI."
MOSI_SET_ID = "SET_ID"
MOSI_DO_SETUP = "DO_SETUP"
MOSI_START_MINING = "START_MINING"
MOSI_STOP_MINING = "STOP_MINING"
MOSI_GOTO_X = "GOTO_X"
MOSI_GOTO_Y = "GOTO_Y"
MOSI_GOTO_Z = "GOTO_Z"
MOSI_REQUEST_COORDS = "REQUEST_COORDS"
MOSI_DISASSEMBLE_ARRAY = "DISASSEMBLE_ARRAY"

MISO_PREFIX = "MISO."
MISO_DONE_SETUPING = "DONE_SETUPING"
MISO_RETURN_COORDS = "RETURN_COORDS"