shell.execute("rm", "*")
shell.execute("wget", "https://raw.githubusercontent.com/LhAlant/ComputerCraftMiningArray/main/master.lua", "startup.lua")
shell.execute("wget", "https://raw.githubusercontent.com/LhAlant/ComputerCraftMiningArray/main/utils.lua", "utils.lua")
shell.execute("wget", "https://raw.githubusercontent.com/LhAlant/ComputerCraftMiningArray/main/protocol.lua", "protocol.lua")
shell.execute("wget", "https://raw.githubusercontent.com/LhAlant/ComputerCraftMiningArray/main/constants.lua", "constants.lua")
