shell.execute("rm", "*")
shell.execute("pastebin", "get", "GWY7p6H6", "startup.lua")
shell.execute("pastebin", "get", "MiA6apfV", "utils.lua")
shell.execute("pastebin", "get", "HciQhcc5", "protocol.lua")
shell.execute("pastebin", "get", "Y3Qy23vH", "constants.lua")